[project]
name = "masterblogapi2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "flask-login>=0.6.3",
    "flask-session>=0.8.0",
    "flask-swagger-ui>=5.21.0",
]
